---
# Couchbase operator via Helm (https://docs.couchbase.com/operator/current/helm-setup-guide.html)
# Chart: couchbase-operator from wrapper in argocd/helm/operator (values from values.yaml).
# Operator is deployed in the couchbase namespace so it manages CouchbaseCluster there (per-namespace operator).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: couchbase-performance
  sources:
    - repoURL: https://couchbase-partners.github.io/helm-charts/
      chart: couchbase-operator
      targetRevision: "2.90.0"
      helm:
        releaseName: operator
        valueFiles: 
         - $values/argocd/manifests/couchbase/operator/values.yaml

    - repoURL: https://github.com/rgordill/couchbase-performance.git
      targetRevision: HEAD
      path: argocd/manifests/couchbase/operator
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: couchbase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
