---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rgordill/couchbase-performance.git
    targetRevision: HEAD
    path: argocd/manifests/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: couchbase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: couchbase.com
      kind: CouchbaseCluster
      jsonPointers:
        - /spec/servers/*/size
